# Generated by Django 6.0.6 on 2026-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GrowthMaster Solutions', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Empowering Business Success', max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, help_text='E.164 format, e.g. +263771234567', max_length=25)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('physical_address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('hero_heading', models.CharField(blank=True, default='Empowering Business Success', max_length=200)),
                ('hero_subheading', models.TextField(blank=True, default='Strategy, Projects, Research & Funding consultancy for SMEs, NGOs and investors in Zimbabwe and the region.')),
                ('about_body', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
