# Generated by Django 6.0.6 on 2026-07-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_secondary',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subheading',
            field=models.TextField(blank=True, default='Strategy, Projects, Research & Funding consultancy for SMEs, NGOs and investors across Africa.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
