# Generated by Django 6.0.6 on 2026-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('social', 'Social Media')], max_length=10)),
                ('category', models.CharField(choices=[('strategy', 'Strategy'), ('projects', 'Projects'), ('research', 'Research'), ('events', 'Events'), ('general', 'General')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='portfolio/thumbs/')),
                ('media_url', models.URLField(blank=True, help_text='YouTube/Vimeo URL for videos; social post URL for embeds')),
                ('embed_code', models.TextField(blank=True, help_text='Raw embed code for social media posts (Instagram, LinkedIn, etc.)')),
                ('media_file', models.FileField(blank=True, help_text='Upload a self-hosted MP4 or full-size photo', upload_to='portfolio/files/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
